name: Run E2E on Fork

on:
  workflow_run:
    workflows: [Receive Fork Review]
    types:
      - completed

jobs:
  # check if approver has write/admin permissions
  check-write-access:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get user permissions to check if it is either "write" or "admin"'
        id: get-permissions
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        with:
          result-encoding: string
          script: |
            var { data } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: '${{ github.event.sender.login }}'
            })
            console.log('data.permission:', data.permission);
            return data.permission;
      - name: 'Fail this workflow if user does not have write permissions'
        if: ${{ steps.get-permissions.outputs.result != 'write' && steps.get-permissions.outputs.result != 'admin' }}
        run: |
          echo "${{ steps.get-permissions.outputs.result }}"
          exit 1
  setup:
    needs: check-write-access
    runs-on: ubuntu-latest
    # check if receive-fork-review workflow completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "commit"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/commit.zip', Buffer.from(download.data));
      - run: unzip commit.zip
      - name: 'Read from artifact zip'
        uses: actions/github-script@v3.1.0
        id: read-artifact
        with:
          result-encoding: string
          script: |
            var fs = require('fs');
            var commit_id = fs.readFileSync('./commit_id', 'utf-8');
            return commit_id.replace(/(\r\n|\n|\r)/gm, "");
      # create status
      - name: Add status to PR
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        env:
          sha: ${{ steps.read-artifact.outputs.result }}
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          run_id: ${{ github.run_id }}
        with:
          result-encoding: string
          script: |
            const { sha, owner, repo, run_id } = process.env;
            github.rest.repos.createCommitStatus({
               owner,
               repo,
               sha,
               state: 'pending',
               context: 'Run E2E tests',
               description: 'E2E tests are now running',
               target_url: `https://github.com/${owner}/${repo}/actions/runs/${run_id}`
            });
      - name: Sleep 10 seconds
        run: sleep 10s
        shell: bash
      - name: Update status of PR
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        env:
          sha: ${{ steps.read-artifact.outputs.result }}
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          run_id: ${{ github.run_id }}
        with:
          result-encoding: string
          script: |
            const { sha, owner, repo, run_id } = process.env;
            github.rest.repos.createCommitStatus({
               owner,
               repo,
               sha,
               state: 'success',
               context: 'Run E2E tests',
               description: 'E2E tests have finished running',
               target_url: `https://github.com/${owner}/${repo}/actions/runs/${run_id}`
            });

  # checkout-repo
  # setup-cache
  # run-E2E
